/*
 * Ruby extension generated by rocaml.
 *
 * Do not edit this file; if you need to change something, edit the script
 * that generated it, rocaml.rb, and please consider sending a patch to its
 * author  Mauricio Fernandez <mfp@acm.org>.
 *
 * This file will be overwritten by rocaml when you run extconf.rb.
 */

#include <ruby.h>
#include <st.h>
#include <string.h>
#include <caml/mlvalues.h>
#include <caml/callback.h>
#include <caml/memory.h>
#include <caml/alloc.h>
#include <caml/fail.h>

VALUE mtest;




static VALUE
do_raise_exception(VALUE klass, char *s)
{
  rb_raise(klass, "%s", s);
  return Qnil; /* not reached */
}

static VALUE
do_raise_exception_tag_aux(VALUE *args)
{
  rb_raise(args[0], "%s", StringValuePtr(args[1]));
  return Qnil;
}

static VALUE
do_raise_exception_tag(VALUE klass, char *s, int *status)
{
  VALUE args[2];
  args[0] = klass;
  args[1] = rb_str_new2(s);
  rb_protect((VALUE (*)(VALUE))do_raise_exception_tag_aux, (VALUE)args, status);
  return Qnil;
}

static VALUE
ocaml_exception_string(value exn)
{
  CAMLparam1(exn);
  CAMLlocal1(str);
  char exception_text[256];
  static value *closure;

  if(closure == NULL) {
    closure = caml_named_value("Printexc.to_string");
  }

  if(closure) {
    str = caml_callback(*closure, exn);

    snprintf(exception_text, 255, "OCaml exception: %s", String_val(str));
    CAMLreturn(rb_str_new2(exception_text));
  } else {
    CAMLreturn(rb_str_new2("OCaml exception"));
  }
}



VALUE test_wrapper__s_print_ex
      (VALUE *exception, int *status, VALUE self)
{
  CAMLparam0();
  CAMLlocal1(ret);

  static value *closure = NULL;

  if(closure == NULL) {
    closure = caml_named_value("test.print");
    if(closure == NULL) {
      *exception = rb_str_new2("Couldn't find OCaml value 'test.print'.");
      CAMLreturn(Qnil);
    }
  }


  ret = caml_callback_exn(*closure, Val_unit);

  if(Is_exception_result(ret)) {
    *exception = ocaml_exception_string(Extract_exception(ret));
    CAMLreturn(Qnil);
  }

  CAMLreturn(Qnil);
}

VALUE test_wrapper__s_print
      (VALUE self)
{
  VALUE ret;
  VALUE exception = Qnil;
  int status = 0;

  ret = test_wrapper__s_print_ex(&exception, &status, self);

  if(exception == Qnil && !status) {
    return ret;
  } else if(status) { /* exception in Ruby -> caml conversions */
    rb_jump_tag(status);
  } else {            /* OCaml exception*/
    rb_raise(rb_eStandardError, StringValuePtr(exception));
  }

  return Qnil; /* never reached */
}


char *argv[] = { NULL };

void Init_test()
{

  caml_startup(argv);
  mtest = rb_define_module("test");
  rb_define_singleton_method(mtest, "print", test_wrapper__s_print, 0);
}
